### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by a455bcd9** [glample/tagger#10]
Hi,

When I use `tagger.py` I sometimes get the following error:

`Floating point exception (core dumped)`

The error appears if there's one of the following lines in the document (for instance):

```
_ _ _
| _ |
_ | _
_ | | 
| | |
```

On the other hand, the following lines "work":

```
A A A
L L L
X L L
L | L
```

I have no line number, but the error happens after line 59. Indeed a dirty fix (eliminate lines with only one-character words) fixed the problem. But I have no idea where the problem is coming from.

**Comment by a455bcd9** [comment]
With `pdb.py` the bug appears at `y_preds = np.array(f_eval(*input))[1:-1]`.

You can reproduce the bug with:

`./tagger.py -m models/english -i input.txt -o output.txt`

With the following content in `input.txt` (the number 39 only):
`39`

**Comment by glample** [comment]
Hi,

I think I understand the issue. During the training, when the model finds an unknown word in the sentence, it will just put a "UNK" token. However, when it finds unknown characters in a word, it will just ignore these characters, there is no "UNK" character symbol. That's a simplification I made during the implementation. It's easy to train the UNK token for words : during the training you can simply replace some rare words (the ones that appear just once in the corpora, for instance) with the UNK token once in a while. Rare characters is not that frequent, so I just thought removing them from a word should not be an issue.

Anyway, what happens in your example is that "_" or "|" will end up being words without any characters inside because these characters were not in the training set. If you try the "a_ a_ a_" sentence it should work. Look at the "mappings.pkl" file in the model (using cPickle), there is a "id_to_char" object that will show you the characters that have embeddings and will not be ignored. To fix this you could go to https://github.com/glample/tagger/blob/master/loader.py#L142
and just add an existing character like "-" to the empty words:

```
for i, x in enumerate(chars):
    if not x:
        chars[i] = [char_to_id['-']]
```

**Comment by a455bcd9** [comment]
Hi,

Thanks for your answer, but this doesn't explain why `39` failed since those characters (converted to zeros) were known.

I think the issue is that `words = line.rstrip().split()` is on line https://github.com/glample/tagger/blob/master/tagger.py#L58 instead of https://github.com/glample/tagger/blob/master/tagger.py#L66 so conversion of numbers to zeros isn't taken into account.

Then, there is the issue for weird unknown characters such as `_`, that can be fixed with your code, in both `prepare_dataset()` https://github.com/glample/tagger/blob/master/loader.py#L142 and `prepare_sentence()`  on line 119.

Don't you think so?

**Comment by glample** [comment]
Oh yeah you are right, this is a serious issue. Thanks for spotting it!
Moving the words split line will indeed do the trick.
