### ISSUE TITLE
Bug in preprocessing of tagger.py

### ISSUE THREAD

**Issue by nreimers** [glample/tagger#15]
Hi,
I think there is a small bug in the preprocessing of tagger.py:

```
        words = line.rstrip().split()
        if line:
            # Lowercase sentence
            if parameters['lower']:
                line = line.lower()
            # Replace all digits with zeros
            if parameters['zeros']:
                line = zero_digits(line)
```

You do the lower() and zero_digits() preprocessing after the input line is split into words. To the neural network, the variable words is passed, i.e., the two preprocessings steps lower and zeros will not be applied if you run the tagger.py file.

**Comment by glample** [comment]
Hi,

Thanks for pointing this out. Indeed there is a small issue here. Actually this pull request https://github.com/glample/tagger/pull/12 tries to fix it. I didn't accept it because I'm not sure it is exactly what I was doing in the paper (I didn't have the time to check yet..).

I think that what I was doing when there the lowercase flag is ON, is that I lowercase the words, but not the characters. So that the lookup table for words will only contain lowercased words, but the lookup table for characters will still contain some uppercase characters. If you take the fix in the pull, and also remove the

```
if parameters['lower']:
    line = line.lower() line = line.lower()
```

in tagger.py, it should work. Words are lowercased in the `prepare_sentence` function. If you take the pull request code but dont remove these 2 lines this will also lowercase characters, but this is not necessary. The idea of lowercasing words is to reduce vocabulary size. Lowercasing characters will reduce number of characters, but characters are not the issue, there are only a few of them.

Anyway, I'll check all this next week and accept the pull / push a fix.
