### ISSUE TITLE
How i can read files " *.mat " and file " *.pkl " file use for what?

### ISSUE THREAD

**Issue by zero76114** [glample/tagger#7]
Dear @glample ,

Can you explain about that. Many thanks.

**Comment by glample** [comment]
A pickle file (.pkl) is a serialized version of your data. It lets you dump to a file the content of some variables, so that you can load them later when you restart the code.
.mat files have basically the same purpose, but are used to dump arrays specifically (it's much faster to store a matrix on the disk using .mat than .pkl, because .pkl tries to optimize the compression, even though an array generally can't be compressed).
The code will automatically load these files, you don't have to do anything particular to load a model.

**Comment by zero76114** [comment]
Thank for your explanation.
